### ISSUE TITLE
Disable power management on the uap0 interface

### ISSUE THREAD

**Issue by Shikartoos** [peebles/rpi3-wifi-station-ap#1]
Hi,

Thank you for providing this.

I am wondering whether it is possible to disable power management on the AP interface uap0.

When I try this command 
`iwconfig uap0 power off` 

I get the following output

> Error for wireless request "Set Power Management (8B2C)"
>     SET failed on device uap0 : Invalid argument.

Thank you,
Shikartoos

**Comment by peebles** [comment]
Boy, I have no idea.  Looks like you can't.

**Comment by Shikartoos** [comment]
Okay, it turned out that I can turn it off using the below command.
`sudo iw uap0 set power_save off`
I guess using **iw** instead of the **iwconfig** is better for the wireless configs in general.

I am closing this issues I guess, thank you!
