### ISSUE TITLE
[Error] Error Caused by Connection Priority

### ISSUE THREAD

**Issue by alpgul** [peebles/rpi3-wifi-station-ap#4]
hello,
i can't start it. I do not know how to run it, can you help me?
```sh
Failed to create interface mon.uap0: -95 (Operation not supported)
uap0: Could not connect to kernel driver
Using interface uap0 with hwaddr b8:27:a1:0f:00:00 and ssid "TESTAP"
Failed to set beacon parameters
uap0: Could not connect to kernel driver
Interface initialization failed
uap0: interface state UNINITIALIZED->DISABLED
uap0: AP-DISABLED
uap0: Unable to setup interface.
uap0: interface state DISABLED->DISABLED
uap0: AP-DISABLED
hostapd_free_hapd_data: Interface uap0 wasn't started
nl80211: deinit ifname=uap0 **disabled_11b_rates=0
```

**Comment by peebles** [comment]
Are your sure you are using a Raspberry Pi 3?  Because it almost looks like your Raspberry does not have the same WIFI chipset as mine.

**Comment by alpgul** [comment]
I solved it. its cause is primarily related. If you are experiencing the same problem, you can click on [this link.](https://raspberrypi.stackexchange.com/questions/87504/raspberry-pi-zero-w-as-a-wifi-repeater/87506#87506)
